image: golang:latest

before_script:
  - go get golang.org/x/lint/golint

make:
  script: make
  artifacts:
    paths:
      - config/crd/egw-namespace.yaml
      - config/crd/bases/egw.acnodal.io*.yaml
      - config/samples/namespace.yaml
      - config/samples/egw_v1_*.yaml
