image: golang:latest

before_script:
  - apt-get update
  - apt-get install -y gettext-base
  # this lets the CI runner clone any repo that the pushing user can
  # clone. We need to clone private repos, e.g.,
  # packet-forwarding-component since this project depends on them.
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/acnodal".insteadOf "https://gitlab.com/acnodal"
  - go get golang.org/x/lint/golint

make:
  script:
  - make SUFFIX=latest
  - ls -l deploy
  - 'curl --silent --show-error --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file deploy/egw-resource-model.yaml "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/manifest/0.0.1/egw-resource-model.yaml"'

  artifacts:
    paths:
      - config
      - deploy/*.yaml
