---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    app.kubernetes.io/component: controller-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller-manager
    spec:
      imagePullSecrets:
      - name: gitlab
      containers:
      - name: manager
        image: ${IMG}
        imagePullPolicy: Always
        command: ["/usr/local/bin/manager", "controller-manager", "--debug"]
      terminationGracePeriodSeconds: 2
