---
apiVersion: epic.acnodal.io/v1
kind: LBServiceGroup
metadata:
  namespace: epic-root
  name: samplehttp
  labels:
    owning-account: root
    owning-serviceprefix: default
spec:
  can-be-shared: yes
  endpoint-template:
    dnsName: "{{.PureLBServiceName}}.{{.LBSGName}}.client.acnodal.io"
    recordTTL: 180
    recordType: A
  envoy-replica-count: 1
  envoy-template:
    envoyAPI: v3
    serialization: yaml
    nodeID: SET_BY_EPIC
    envoyResources:
      endpoints:
      - name: SET_BY_EPIC
        value: |
          cluster_name: {{.ClusterName}}
          {{- if .Endpoints}}
          endpoints:
          - lb_endpoints:
          {{- range .Endpoints}}
            - endpoint:
                address:
                  socket_address:
                    address: {{.Spec.Address}}
                    protocol: {{.Spec.Port.Protocol | ToUpper}}
                    port_value: {{.Spec.Port.Port}}
          {{- end}}
          {{- end}}
      clusters:
      - name: SET_BY_EPIC
        value: |
          name: {{.ClusterName}}
          connect_timeout: 2s
          type: EDS
          eds_cluster_config:
            eds_config:
              resource_api_version: V3
              api_config_source:
                api_type: GRPC
                transport_api_version: V3
                grpc_services:
                - envoy_grpc:
                    cluster_name: eds-server
          lb_policy: ROUND_ROBIN
      listeners:
      - name: SET_BY_EPIC
        value: |
          name: {{.PortName}}
          address:
            socket_address:
              address: 0.0.0.0
              port_value: {{.Port}}
              protocol: {{.Protocol | ToUpper}}
          filter_chains:
            - filters:
              - name: envoy.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                  stat_prefix: {{ .ServiceName }}
                  route_config:
                    name: local_route
                    virtual_hosts:
                      - name: purelb
                        domains: ["*"]
                        routes:
                          - match:
                              prefix: "/"
                            route:
                              weighted_clusters:
                                total_weight: {{ .TotalWeight }}
                                clusters:
                                {{- range $i, $cl := .Clusters}}
                                - name: {{$cl}}
                                  weight: {{ $.ClusterWeight }}
                                {{- end}}
                  http_filters:
                    - name: envoy.router
