apiVersion: epic.acnodal.io/v1
kind: EPIC
metadata:
  namespace: epic
  name: epic
spec:
  xds-image: quay.io/3scale/marin3r:v0.7.0
  eds-image: registry.gitlab.com/acnodal/xds-operator:latest
  envoy-image: registry.gitlab.com/acnodal/epic/envoy:latest
  base:
    gue-endpoint:
      epic-address: 192.168.1.40
    gue-ingress-nics:
    - enp1s0
