apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
  name: controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/component: controller-manager
