# permissions for end users to view epics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: epic-viewer-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - epics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - epics/status
  verbs:
  - get
