# permissions for end users to edit epics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: epic-editor-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - epics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - epics/status
  verbs:
  - get
