# permissions for end users to edit gwclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gwcluster-editor-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - gwclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - gwclusters/status
  verbs:
  - get
