# permissions for end users to view gwproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gwproxy-viewer-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - gwproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - gwproxies/status
  verbs:
  - get
