# permissions for end users to edit gwproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gwproxy-editor-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - gwproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - gwproxies/status
  verbs:
  - get
