# permissions for end users to edit gwroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gwroute-editor-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - gwroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - gwroutes/status
  verbs:
  - get
