# permissions for end users to view gwroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gwroute-viewer-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - gwroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - gwroutes/status
  verbs:
  - get
