# permissions for end users to edit lbservicegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lbservicegroup-editor-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - lbservicegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - lbservicegroups/status
  verbs:
  - get
