# permissions for end users to view lbservicegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lbservicegroup-viewer-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - lbservicegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - lbservicegroups/status
  verbs:
  - get
