# permissions for end users to view loadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadbalancer-viewer-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - loadbalancers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - loadbalancers/status
  verbs:
  - get
