# permissions for end users to view endpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remoteendpoint-viewer-role
rules:
- apiGroups:
  - egw.acnodal.io
  resources:
  - remoteendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egw.acnodal.io
  resources:
  - remoteendpoints/status
  verbs:
  - get
