# permissions for end users to edit remoteendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remoteendpoint-editor-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - remoteendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - remoteendpoints/status
  verbs:
  - get
