# permissions for end users to edit servicegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicegroup-editor-role
rules:
- apiGroups:
  - egw.acnodal.io
  resources:
  - servicegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egw.acnodal.io
  resources:
  - servicegroups/status
  verbs:
  - get
