# permissions for end users to edit serviceprefixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceprefix-editor-role
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - serviceprefixes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - serviceprefixes/status
  verbs:
  - get
