# permissions for end users to view serviceprefixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceprefix-viewer-role
rules:
- apiGroups:
  - egw.acnodal.io
  resources:
  - serviceprefixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egw.acnodal.io
  resources:
  - serviceprefixes/status
  verbs:
  - get
