---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: egw
  name: egw-operator
  namespace: acnodal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egw
    component: egw-operator
  name: egw-operator
  namespace: acnodal
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: egw
      component: egw-operator
  template:
    metadata:
      labels:
        app: egw
        component: egw-operator
    spec:
      imagePullSecrets:
      - name: gitlab
      containers:
      - args:
        image: registry.gitlab.com/acnodal/egw-operator/egw-operator:latest
        imagePullPolicy: Always
        name: egw-operator
        ports:
        - name: http
          containerPort: 8080
          hostPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: true
          capabilities: 
            add:
            - NET_ADMIN
      hostNetwork: true
      serviceAccountName: egw-operator
      terminationGracePeriodSeconds: 0
