---
apiVersion: egw.acnodal.io/v1
kind: ServiceGroup
metadata:
  namespace: egw-sample
  name: sample
  labels:
    owning-account: sample
    owning-serviceprefix: default
spec:
  auth-creds: fredfredfredfred
  envoy-image: registry.gitlab.com/acnodal/envoy-for-egw:latest
---
apiVersion: egw.acnodal.io/v1
kind: ServiceGroup
metadata:
  namespace: egw-sample
  name: sample2
  labels:
    owning-account: sample
    owning-serviceprefix: non-default
spec:
  auth-creds: wilmawilmawilma!
  envoy-image: registry.gitlab.com/acnodal/envoy-for-egw:latest
