---
apiVersion: egw.acnodal.io/v1
kind: ServiceGroup
metadata:
  namespace: egw-sample
  name: sample
spec:
  auth-creds: fredfredfredfred
  # FIXME: at some point we'll want to use "latest" instead of
  # "adamd-dev". At that point we can remove this field and the one
  # below since the CRD default is "latest"
  envoy-image: registry.gitlab.com/acnodal/envoy-for-egw:adamd-dev
---
apiVersion: egw.acnodal.io/v1
kind: ServiceGroup
metadata:
  namespace: egw-sample
  name: sample2
spec:
  auth-creds: wilmawilmawilma!
  envoy-image: registry.gitlab.com/acnodal/envoy-for-egw:adamd-dev
