apiVersion: egw.acnodal.io/v1
kind: LoadBalancer
metadata:
  namespace: egw-sample
  name: sample
spec:
  service-group: sample
  public-address: 192.168.77.7
  public-ports:
  - port: 8080
    protocol: tcp
