apiVersion: epic.acnodal.io/v1
kind: EPIC
metadata:
  namespace: epic
  name: epic
spec:
  eds-image: registry.gitlab.com/acnodal/xds-operator:latest
  base:
    gue-endpoint:
      epic-address: 192.168.1.40
    gue-ingress-nics:
    - enp1s0
