apiVersion: epic.acnodal.io/v1
kind: EPIC
metadata:
  namespace: epic
  name: epic
spec:
  eds-image: registry.gitlab.com/acnodal/xds-operator:latest
  # If you change the envoy-image, please also change the epic/devops project epic-data-model.yml to match
  envoy-image: registry.gitlab.com/acnodal/epic/envoy:latest
  base:
    gue-endpoint:
      epic-address: 192.168.1.40
    gue-ingress-nics:
    - enp1s0
