---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  labels:
    app.kubernetes.io/component: node-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: node-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/component: node-agent
    spec:
      imagePullSecrets:
      - name: gitlab
      containers:
      - name: agent
        image: ${IMG}
        imagePullPolicy: Always
        command: ["/usr/local/bin/manager", "node-agent", "--debug"]
        env:
        - name: EPIC_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: EPIC_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: /opt/acnodal/bin
          name: pfctools
        - mountPath: /sys/fs/bpf
          name: bpf
        - mountPath: /run
          name: run
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      terminationGracePeriodSeconds: 2
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: pfctools
        hostPath:
          path: /snap/epic-microk8s/current/opt/acnodal/bin
      - name: bpf
        hostPath:
          path: /sys/fs/bpf
      - name: run
        emptyDir: {}
