name: Build

on: [push, pull_request]

jobs:
  tar:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with: {submodules: recursive}

    - uses: actions/setup-go@v4
      with: {go-version: '=1.19.8'}

    - name: Decide what we're going to call this
      run: |
        if [[ ${{ github.ref }} == refs/tags/* ]]; then
          echo "TAG_SPECIFIC=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          echo "TAG_SPECIFIC=${{ github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        fi
        echo $GITHUB_ENV

    - name: Make
      run: |
        make SUFFIX=${TAG_SPECIFIC} all docker-build

    - name: Push
      run: |
        docker login -u epic-gateway+github_actions -p ${{ secrets.QUAY_EPIC_GATEWAY }} quay.io
        make SUFFIX=${TAG_SPECIFIC} go-push docker-push
      if: startsWith(github.ref, 'refs/tags/')
